### ISSUE TITLE
App won't open after logging in with email

### ISSUE THREAD

**Issue by canaryminer13** [jenius-apps/beeskie#4]
After logging in with my email and the app password from my account whenever I try to open Beeskie the app closes instantly. There's no process running in task manager but if I terminate the app via Windows app settings I can reopen it and try to log in again. It does work if I use my Bluesky handle but using email is not working.

**Comment by dpaulino** [comment]
Thank you for the report! I will investigate

**Comment by canaryminer13** [comment]
[Uploading Recording 2024-11-21 103711 (1).zip…]()

Let me know if you can't see it. I was going to log out and try to recreate the issue but now it's closing itself even when I'm logged in.

**Comment by RedStraggler** [comment]
Also having this issue, Windows 10. App would not let me login with handle, alternating between "rate limit exceeded" and "authentication" errors. Logging in with e-mail caused the app to close, after seemingly completing the login process, and now upon opening Beeskie I'm met with the splash logo for some seconds until it closes again, no running process in Task Manager.

**Comment by nephrops** [comment]
Same here with Win 11. The app accepts the login via email and shutdown immediately

**Comment by dpaulino** [comment]
@canaryminer13 @RedStraggler @nephrops can you all share information about your device?

OS version
Brand
Model 

Do you also mind sharing your handles? Or if you prefer, you can share this info via email: beeskie_app@outlook.com. 

I'm trying to see if there's a pattern to these issues. Because I can't seem to reproduce the crash myself just be using my email.

**Comment by dpaulino** [comment]
Just a guess so far, but I think this may be the root cause

![image](https://github.com/user-attachments/assets/caee6534-adfa-4b5f-adba-9d34a2ddc6a0)

**Comment by dpaulino** [comment]
Confirmed I was able to reproduce this. Fixed: 1153eea6fc227df0c7e1b3e74093579c5a1502ee
